// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsevudeuwedgofdwemsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzZXZ1ZGV1d2VkZ29mZHdlbXNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NzA0NTUsImV4cCI6MjA2MDI0NjQ1NX0.4jXlw8uCN1ukjhoKLXmmPTx1RTRq_-r06Hr8MCQf9wE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);